MODEL:
    PRETRAIN_CHOICE: 'imagenet'
    METRIC_LOSS_TYPE: 'triplet'
    IF_LABELSMOOTH: 'on'
    IF_WITH_CENTER: 'no'
    NAME: 'ViT-B-16'
    STRIDE_SIZE: [16, 16]
    ID_LOSS_WEIGHT: 0.25 # ID LOSS
    TRIPLET_LOSS_WEIGHT: 1.0 # Triplet LOSS
    I2T_LOSS_WEIGHT: 1.0 # i2t_ce_loss
    I2T_WEIGHT: 1.0 # i2t_loss
    T2I_WEIGHT: 1.0 # t2i_loss
    VIFI_WEIGHT: '/home/Newdisk/luowenlong/Projects/ViFi-weight/vifi_weight.pth'
    USE_VIFI_WEIGHT: False
    PBP_PROMPT_LEN: 1
    PBP_PROMPT_DEEP: 9
    PBP_CAMERA: True
    PBP_META: True
    PBP_ALT: True
    PBP_DIST: True
    PBP_ANGLE: True
    PBP_ALT_BINS: 18
    PBP_DIST_BINS: 18
    PBP_ANGLE_BINS: 3
    USE_ADAPTER: True
    ENABLE_VCAH: False
    ENABLE_QATW: False
    VCAH_WEIGHT: 0.05
    ENABLE_ATT_POOL: False
    INSTANCE_NORM_NECK: False

    VIAL_LOSS_WEIGHT: 0.5  
    VIAL_LAMBDA: 0.5       
    VIAL_BETA: 5.0    
    VIAL_MARGIN: 0.5       
    VIAL_TYPE: 'hnm' 
INPUT:
    SIZE_TRAIN: [384, 192]
    SIZE_TEST: [384, 192]
    PROB: 0.5 # random horizontal flip
    RE_PROB: 0.5 # random erasing
    PADDING: 10
    PIXEL_MEAN: [0.485, 0.456, 0.406]
    PIXEL_STD: [0.229, 0.224, 0.225]

DATALOADER:
    SAMPLER: 'softmax_triplet'
    NUM_INSTANCE: 4
    NUM_WORKERS: 8
    SEQ_LEN: 8

SOLVER:
    STAGE1:
        IMS_PER_BATCH: 16
        OPTIMIZER_NAME: 'Adam'
        BASE_LR: 0.00035
        WARMUP_LR_INIT: 0.00001
        LR_MIN: 1e-6
        WARMUP_METHOD: 'linear'
        WEIGHT_DECAY: 1e-4
        WEIGHT_DECAY_BIAS: 1e-4
        MAX_EPOCHS: 120
        CHECKPOINT_PERIOD: 60
        LOG_PERIOD: 10
        WARMUP_EPOCHS: 5

    STAGE2:
        IMS_PER_BATCH: 8
        OPTIMIZER_NAME: 'Adam'
        BASE_LR: 0.0001
        WARMUP_METHOD: 'linear'
        WARMUP_ITERS: 10
        WARMUP_FACTOR: 0.1
        WEIGHT_DECAY: 0.00025
        WEIGHT_DECAY_BIAS: 0.0001
        LARGE_FC_LR: False
        MAX_EPOCHS: 80
        CHECKPOINT_PERIOD: 5
        LOG_PERIOD: 60
        EVAL_PERIOD: 1
        BIAS_LR_FACTOR: 2

        STEPS: []
        GAMMA: 0.1

    STAGE3:
        IMS_PER_BATCH: 8
        OPTIMIZER_NAME: "Adam"
        BASE_LR: 0.00001
        MAX_EPOCHS: 30
        WEIGHT_DECAY: 0.00025
        WEIGHT_DECAY_BIAS: 0.0001
        STEPS: []
        GAMMA: 0.1
        WARMUP_METHOD: 'linear'
        WARMUP_ITERS: 100
        WARMUP_FACTOR: 0.01
        CHECKPOINT_PERIOD: 5
        LOG_PERIOD: 50
        EVAL_PERIOD: 5
        DFGS_K_NEIGHBORS: 8
        DFGS_M_DIFFICULTY: 2
        DFGS_SHUFFLE: True
        DFGS_UPDATE_EVERY: 5

TEST:
    EVAL: True
    IMS_PER_BATCH: 16
    RE_RANKING: False
    WEIGHT: ''
    NECK_FEAT: 'before'
    FEAT_NORM: 'yes'
    ALL_FRAMES: False
    DISTANCE: 'cosine'
    SEQ_LEN: 16

DATASETS:
    NAMES: ('detreidx')
    ROOT_DIR: ('data')
OUTPUT_DIR: 'output_original/VSLACLIP_v6'
#ROOT_DIR: ('/home/rashid/models/datasets/DETREIDX')
